"""FastAPI application entry point."""

from __future__ import annotations

from pathlib import Path

from fastapi import FastAPI
from fastapi.staticfiles import StaticFiles

from app.api.circuits import router as circuits_router
from app.api.generate import router as generate_router


GENERATED_DIR = Path("app/generated")
GENERATED_DIR.mkdir(parents=True, exist_ok=True)


app = FastAPI(
    title="Digital Logic AI",
    version="0.1.0",
)


# Circuit PNGs generated by /api/generate are served from this URL prefix.
app.mount(
    "/generated",
    StaticFiles(directory=str(GENERATED_DIR)),
    name="generated",
)

app.include_router(generate_router)
app.include_router(circuits_router)


@app.get("/")
def root():
    return {
        "message": "Digital Logic AI backend is running"
    }


@app.get("/health")
def health():
    return {
        "status": "ok"
    }